const YIELD_OPERATIONS = 0x1fff
const YIELD_DURATION = 1

namespace decrypt {
	namespace util {
		def shouldYield(ctr int) bool {
			return !speedtest.IS_SPEEDTEST && (ctr & YIELD_OPERATIONS) == 0
		}

		def yield(fn fn()) {
			dynamic.setTimeout(fn, YIELD_DURATION)
		}

		def initKey(data DecryptData) {
			if speedtest.IS_SPEEDTEST {
				# don't randomize key in speedtest mode, since we want comparable results
				return
			}
			const rng = (Math.random * (-1 as dynamic >>> 0)) as int
			for i in 0 .. data.keyspace {
				data.key[i >> 3] ^= ((rng >>> i) & 1) << (i & 7)
			}
		}

		def nextKey(data DecryptData) {
			# increment key. yes this is slightly cursed
			# using a variable is 3 bytes longer, but compresses better
			var shift int
			for i in 0 .. data.keyspace {
				shift = (1 << (i & 7))
				if (data.arr[1 + (i >> 3)] ^= shift) & shift as dynamic {
					break
				}
			}
		}
	}
}