const NAME = "jspowobfdata"

@entry if !IS_WEBPAGE
def entrypoint {
	const data = document.querySelectorAll("[\(NAME)]") as List<dynamic>
	for element in data {
		element.addEventListener("click", (ev) => onclick(ev))
	}
}

def onclick(event dynamic) {
	event.stopPropagation()

	const element = event.target
	const encoded = element.getAttribute(NAME)
	if !encoded {
		return
	}
	const decoded = decodeBase64(encoded)

	# remove attribute to prevent multiple clicks
	element.removeAttribute(NAME)
	disable(element)

	const decrypter = Decrypter.fromData(decoded)
	decrypter.shuffleKey
	decrypter.decrypt((done) => {
		element.outerHTML = done
	})
}


@import
var document dynamic

@import
var Uint8Array dynamic

@import
var crypto dynamic

@import
var TextDecoder dynamic