namespace decrypt {
	if IMPLEMENTATION == .SUBTLECRYPTO {
		def decrypt(data DecryptData, fn fn(dynamic)) {
			subtlecrypto.decrypt(data, fn)
		}
	}

	namespace subtlecrypto {
		def decrypt(data DecryptData, fn fn(dynamic)) {
			util.initKey(data)
			_decrypt(data, fn, 0)
		}

		def _decrypt(data DecryptData, fn fn(dynamic), ctr int) {
			crypto.subtle.importKey(
				"raw",
				data.key,
				{ "name": "AES-GCM" },
				false,
				["decrypt"]
			).then((key) => {
				return crypto.subtle.decrypt(
					{
						"name": "AES-GCM",
						"iv": data.nonce
					},
					key,
					data.ciphertext
				)
			}).then(HAS_LOGGING ? (r) => {
				log("\(ctr) steps")
				fn(r)
			} : fn)["catch"](() => {
				util.nextKey(data)
				if util.shouldYield(++ctr) {
					util.yield(() => {
						_decrypt(data, fn, ctr)
					})
				} else {
					_decrypt(data, fn, ctr)
				}
			})
		}
	}
}