namespace decrypt {
	if IMPLEMENTATION == .WASM_HYBRID {
		def decrypt(data DecryptData, fn fn(dynamic)) {
			if worker.delegateToWorker {
				worker.decryptInWorker(data, fn)
				return
			}
			if wasm.isWASMAvailable {
				wasm.loadDefaultWASM.then((w) => {
					wasm.decrypt(data, fn, w)
				}, () => {
					wasm.supportsWasmFlag = false
					subtlecrypto.decrypt(data, fn)
				})
			} else {
				subtlecrypto.decrypt(data, fn)
			}
		}
	}

	namespace wasm {
		var supportsWasmFlag = true
		def isWASMAvailable bool {
			return dynamic.typeof(WebAssembly) != "undefined" && supportsWasmFlag
		}
	}
}