namespace worker {
	var script = WORKER && !isWorker ? document.currentScript : null
	var pool = List<Worker>.new as Pool
	var pendingRequests = 0
	var requestCounter = 0

	@skip if !WORKER
	def decryptInWorker(data decrypt.DecryptData, fn fn(dynamic)) {
		pool.work(data, fn)
	}

	var blobbed string = null
	def source string {
		# find the source code for the worker (it's our own file)
		var src = script.src
		if src is string && src != "" {
			return src
		}

		# it has to be in the content itself if it's not in src
		# => script.text

		# if we use WASM and it's inlined, we can use a data: URI
		if IMPLEMENTATION.isWASM && decrypt.wasm.DEFAULT_WASM_URL == "" {
			return "data:," + script.text
		}

		# we need to use a Blob to create a URL for the worker because a data:
		# URI would "lose" the origin and the worker would not be able to access
		# the WASM if it was loaded from a relative path

		# we cache the blob URL so we don't create it multiple times.
		# While we could immediately revoke it again, this would use more code
		# and just keeping a few kb in memory is not a problem.
		if blobbed == null {
			blobbed = URL.createObjectURL(Blob.new([script.text]))
		}
		return blobbed
	}

	def delegateToWorker bool {
		return WORKER && !isWorker && supportsWorkers
	}

	def isWorker bool {
		return WORKER && dynamic.typeof(document) == "undefined"
	}

	var supportsWorkersFlag = true
	def supportsWorkers bool {
		return WORKER && dynamic.typeof(Worker) != "undefined" && supportsWorkersFlag
	}

	def getThreads int {
		var cores = navigator.hardwareConcurrency as int
		if cores < WORKER_SCALING_MIN {
			cores = WORKER_SCALING_MIN
		} else if cores > WORKER_SCALING_MAX {
			cores = WORKER_SCALING_MAX
		}
		return cores
	}

	def workerEntry {
		dynamic.addEventListener("message", (ev) => {
			var data = ev.data as Message
			decrypt.decrypt(data.data, (decrypted) => {
				dynamic.postMessage(Message.new(data.id, null, decrypted))
			})
		})
	}

	class Message {
		var id int
		var data decrypt.DecryptData
		var result Uint8Array
	}
}