namespace page {
  var estimatedSpeed = 0

  @entry if BTARGET == .PAGE
  def webpage {
    const form = document.querySelector("#obfuscate")
    form.addEventListener("submit", (ev) => onsubmit(ev))

    const keyspaceInput = document.querySelector("#keyspace-input")
    keyspaceInput.addEventListener("input", () => onupdate)
    onupdate

    const form2 = document.querySelector("#deobfuscate")
    form2.addEventListener("submit", (ev) => ondeobfuscate(ev))

    const estimateSpeedButton = document.querySelector("#estimate-speed-button")
    estimateSpeedButton.addEventListener("click", () => {
      dom.disable(estimateSpeedButton)
      speedtest.performSpeedTest((speed) => {
        estimatedSpeed = speed as int
        log("estimated speed: \(estimatedSpeed) ops/sec")
        onupdate
        estimateSpeedButton.remove()
      })
    })
  }

  def onupdate {
    const keyspaceInput = document.querySelector("#keyspace-input")
    const keyspaceEstimate = document.querySelector("#keyspace-estimate")

    const value = dynamic.parseInt(keyspaceInput.value) as int
    keyspaceEstimate.textContent = "\(value) bits."

    if estimatedSpeed > 0 {
      const totalOps = 2.0 ** value
      const seconds = totalOps / estimatedSpeed / 2 # average case is half

      keyspaceEstimate.textContent = "\(value) bits. Estimated bruteforce time: \((seconds as dynamic).toFixed(3)) seconds."
    }
  }

  def onsubmit(event dynamic) {
    event.preventDefault()
    const input = document.querySelector("#data-input")
    const keyspaceInput = document.querySelector("#keyspace-input")

    const data = input.value as string
    const keyspace = dynamic.parseInt(keyspaceInput.value) as int

    encrypt.encrypt(data, keyspace).then((encoded) => {
      const output = document.querySelector("#output")
      output.removeAttribute("hidden")
      const outputData = document.querySelectorAll(".obfuscated-data") as List<dynamic>
      for element in outputData {
        element.innerText = encoded
      }
    })
  }

  def ondeobfuscate(event dynamic) {
    event.preventDefault()

    const submitButton = document.querySelector("#deobfuscate button")
    if submitButton.disabled {
      return
    }

    dom.disable(submitButton)

    const output = document.querySelector("#deobfuscated-output")
    output.setAttribute("hidden", "")

    const input = document.querySelector("#deobfuscate-input")
    const encoded = input.value as string
    const decoded = base64.decode(encoded)

    const start = performance.now()

    decrypt.decrypt(decoded, (buffer) => {
      output.removeAttribute("hidden")
      const outputData = document.querySelector("#deobfuscated-data")
      outputData.value = TextDecoder.new().decode(Uint8Array.new(buffer))

      dom.enable(submitButton)

      const end = performance.now()

      const speedOutput = document.querySelector("#deobfuscated-speed")
      const duration = end - start
      speedOutput.textContent = "Deobfuscated in \(((duration as dynamic) / 1000).toFixed(3))s."
    })
  }
}
