const BTARGET = BuildTarget.MAIN

enum BuildTarget {
  MAIN
  PAGE
  WEBLIB
  SPEEDTEST
}

const IMPLEMENTATION = Implementation.SUBTLECRYPTO

enum Implementation {
  SUBTLECRYPTO
  WASM
  WASM_HYBRID

  def isWASM bool {
    return self == .WASM || self == .WASM_HYBRID
  }
}

# Use Web Workers to offload decryption work from the main thread.
# This increases bundle size by around 700 bytes.
# Recommended if you use WASM implementations, since those don't yield
# to the event loop during decryption.
const WORKER = false
# If true, we will be tolerant of the worker dying. This can happen due to CSP
# restrictions or TOR browser settings. Note that this is different from window.Worker
# simply being undefined, which is handled independently of this flag.
const WORKER_TOLERANT = true
# If true, we will scale the number of workers based on the number of CPU cores.
# This increases bundle size by around 150 bytes.
# Default is to use a single worker.
const WORKER_SCALING = false
const WORKER_SCALING_MIN = 1
const WORKER_SCALING_MAX = 16

# Use native Uint8Array.fromBase64 and toBase64 methods if available. Saves around 400 bytes.
# For compatibility reasons, this is disabled by default.
# Compat: https://caniuse.com/mdn-javascript_builtins_uint8array_tobase64
# (Widely available since September 2025)
const NATIVE_BASE64 = false
